apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: perf-monitoring
    app.kubernetes.io/component: perf-grafana
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: grafana-perf-monitoring
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: grafana-perf-monitoring
    app.kubernetes.io/part-of: perf-monitoring
    component: perf-grafana
  name: grafana-perf-monitoring
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: perf-monitoring
      app.kubernetes.io/instance: grafana-perf-monitoring
      component: perf-grafana
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: perf-monitoring
        app.kubernetes.io/component: perf-grafana
        app.kubernetes.io/instance: grafana-perf-monitoring
        app.kubernetes.io/name: perf-monitoring
        component: perf-grafana
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: grafana-secret
        image: quay.io/redhat-user-workloads-stage/msawood-tenant/perf-monitoring/grafana-perf-monitoring@sha256:a050064ff9680f8cb8c6b772ebb5cd77c2214b9c0d8395f878f6425ba72aede9
        imagePullPolicy: Always
        name: perf-grafana
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 250m
            memory: 256Mi
        securityContext:
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /etc/grafana
          name: grafana-config
        - mountPath: /var/lib/grafana
          name: grafana-data
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          name: grafana-config
        name: grafana-config
      - emptyDir: {}
        name: grafana-data
status: {}
