apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: perf-grafana
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: grafana-perf-monitoring
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: grafana-perf-monitoring
    app.kubernetes.io/part-of: perf-monitoring
  name: grafana-perf-monitoring
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/component: perf-grafana
    app.kubernetes.io/instance: grafana-perf-monitoring
    app.kubernetes.io/name: perf-monitoring
status:
  loadBalancer: {}
