apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: perf-prometheus
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: prometheus-perf-monitoring
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: prometheus-perf-monitoring
    app.kubernetes.io/part-of: perf-monitoring
  name: prometheus-perf-monitoring
spec:
  ports:
  - name: http
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app.kubernetes.io/component: perf-prometheus
    app.kubernetes.io/instance: prometheus-perf-monitoring
    app.kubernetes.io/name: perf-monitoring
status:
  loadBalancer: {}
