apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: grafana-perf-monitoring
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/msawood-tenant/perf-monitoring/grafana-perf-monitoring@sha256:a050064ff9680f8cb8c6b772ebb5cd77c2214b9c0d8395f878f6425ba72aede9
        name: perf-grafana
        resources: {}
status: {}
