apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: grafana-perf-monitoring
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/msawood-tenant/perf-monitoring/grafana-perf-monitoring@sha256:fe04b25ed14c2ab79902520af01cf2e4fcab65ed0d701bd0f0bf6d04fe4545b1
        name: perf-grafana
        resources: {}
status: {}
