apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: grafana-perf-monitoring
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: grafana-perf-monitoring
    app.kubernetes.io/part-of: perf-monitoring
  name: grafana-perf-monitoringiqkd
spec:
  port:
    targetPort: 3000
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: grafana-perf-monitoring
    weight: 100
status: {}
